### ISSUE TITLE
Plan out the OpenFisca-US computation tree

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#217]
I think this will clarify a lot of things and shed a bit of light on how best to structure the repo variables: planning out the computation tree. I've made a start, with a few suggestions for general strategies (feel free to disagree!) on [this doc](https://docs.google.com/document/d/1CgtQqQXvq0IB3tK-wqLj_oJ7JH_dxGaCQh7-HZllZcc/edit?usp=sharing). @MaxGhenis @nmrodelo @tolaouk feel free to add any tax, SNAP, or other variables if you've got clearer ideas.

**Comment by MaxGhenis** [comment]
I think we've gotten more organized and flexible about this, and the tree is becoming more of a web as we do more programs. At this point I think we'd be better off creating visualizations of the dependencies as we've implemented them rather than building off the doc. So closing, but feel free to reopen if you disagree.
