### ISSUE TITLE
Verify that Tax-Calculator 2020 EITC bug doesn't affect OpenFisca US

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#769]
See https://github.com/PSLmodels/Tax-Calculator/issues/2660

**Comment by MaxGhenis** [comment]
Verified: the EITC amounts do not vary depending on the unemployment benefits received ([notebook](https://colab.research.google.com/drive/1CFTnheX3eTUdDaVaN680fh-5NHFtNAoq?usp=sharing)). The EITC amounts themselves do differ a bit from Tax-Calculator though.

**Comment by martinholmer** [comment]
@MaxGhenis said just before closing issue #769:

> Verified: the EITC amounts do not vary depending on the unemployment benefits received  (link to a notebook). The EITC amounts themselves do differ a bit in this example though: Tax-Calculator reports $6,660, vs. our $6,596.8

OpenFisca-US is getting the wrong EITC amount in the two cases you examined because there are no 2020 values for the phase-out start amount in the `parameters/irs/credits/eitc/phaseout/start.yaml` file.  Not sure why they are missing because the `joint_bonus.yaml` file in the same directory has 2020 values.  Perhaps the absence of the 2020 values in the `start.yaml` file is related to the fact that the URL in that file for the IRS document containing the 2020 values is broken.

@nikhilwoodruff

**Comment by MaxGhenis** [comment]
Thank you @martinholmer! Filed https://github.com/PolicyEngine/openfisca-us/issues/790.
